### ISSUE TITLE
More control over blocking

### ISSUE THREAD

**Issue by Mitchell3514** [austinhuang0131/dtel#177]
Firstly, block channels instead of numbers, as numbers may change.
Secondly, give people the option to block an entire guild instead of just a channel (now number).
And these blocks should count guild-wide.

**Comment by Rexogamer** [comment]
I’m for all but the third. Some servers may have a channel for each user or smth, and different users may want calls from different numbers

**Comment by Mitchell3514** [comment]
Let's make it an option then

**Comment by SunburntRock89** [comment]
Although blocking numbers is more true to life

**Comment by Mitchell3514** [comment]
Changed blocking to block the guild/user (dm) instead
